lsi: false
safe: true
domain: cooperationtalkseries.github.io
url: https://cooperationtalkseries.github.io
baseurl: /docs/
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
